# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import imageUpload.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUpload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to=imageUpload.models.scramble_uploaded_filename, verbose_name='Uploaded image'),
        ),
    ]
